-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["managed"] = {
            [1] = {
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["split_tree"] = {
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["windowid"] = 6291459,0,
                                                    ["level"] = 1,0,
                                                    ["sizepolicy"] = "full",
                                                    ["checkcode"] = 1,0,
                                                    ["geom"] = {
                                                        ["x"] = 0,0,
                                                        ["w"] = 1360,0,
                                                        ["h"] = 726,0,
                                                        ["y"] = 0,0,
                                                    },
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                },
                                            },
                                            ["name"] = "WGroupCW",
                                            ["sizepolicy"] = "full",
                                            ["geom"] = {
                                                ["x"] = 3,0,
                                                ["w"] = 1360,0,
                                                ["h"] = 726,0,
                                                ["y"] = 23,0,
                                            },
                                            ["switchto"] = true,
                                            ["type"] = "WGroupCW",
                                            ["level"] = 0,0,
                                        },
                                    },
                                    ["name"] = "Tiling Frame<2>",
                                    ["type"] = "WFrame",
                                    ["mode"] = 1,0,
                                },
                            },
                            ["tls"] = 752,0,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["brs"] = 16,0,
                            ["type"] = "WSplitSplit",
                            ["dir"] = "vertical",
                        },
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["x"] = 0,0,
                            ["w"] = 1366,0,
                            ["h"] = 768,0,
                            ["y"] = 0,0,
                        },
                        ["level"] = 0,0,
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                    },
                },
                ["name"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
                ["geom"] = {
                    ["x"] = 0,0,
                    ["w"] = 1366,0,
                    ["h"] = 768,0,
                    ["y"] = 0,0,
                },
                ["type"] = "WGroupWS",
                ["level"] = 0,0,
            },
            [2] = {
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["split_tree"] = {
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["windowid"] = 8388616,0,
                                                    ["level"] = 1,0,
                                                    ["sizepolicy"] = "full",
                                                    ["checkcode"] = 2,0,
                                                    ["geom"] = {
                                                        ["x"] = 0,0,
                                                        ["w"] = 1360,0,
                                                        ["h"] = 726,0,
                                                        ["y"] = 0,0,
                                                    },
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                },
                                            },
                                            ["name"] = "WGroupCW<1>",
                                            ["sizepolicy"] = "full",
                                            ["geom"] = {
                                                ["x"] = 3,0,
                                                ["w"] = 1360,0,
                                                ["h"] = 726,0,
                                                ["y"] = 23,0,
                                            },
                                            ["switchto"] = true,
                                            ["type"] = "WGroupCW",
                                            ["level"] = 0,0,
                                        },
                                    },
                                    ["name"] = "Tiling Frame<1>",
                                    ["type"] = "WFrame",
                                    ["mode"] = 1,0,
                                },
                            },
                            ["tls"] = 752,0,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["brs"] = 16,0,
                            ["type"] = "WSplitSplit",
                            ["dir"] = "vertical",
                        },
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["x"] = 0,0,
                            ["w"] = 1366,0,
                            ["h"] = 768,0,
                            ["y"] = 0,0,
                        },
                        ["level"] = 0,0,
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<1>",
                    },
                },
                ["name"] = "WGroupWS<1>",
                ["sizepolicy"] = "full",
                ["geom"] = {
                    ["x"] = 0,0,
                    ["w"] = 1366,0,
                    ["h"] = 768,0,
                    ["y"] = 0,0,
                },
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
                ["switchto"] = true,
                ["type"] = "WGroupWS",
                ["level"] = 0,0,
            },
            [3] = {
                ["managed"] = {
                    [1] = {
                        ["managed"] = {
                        },
                        ["name"] = "*scratchpad*",
                        ["sizepolicy"] = "free_glue",
                        ["bottom"] = true,
                        ["geom"] = {
                            ["x"] = 363,0,
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 144,0,
                        },
                        ["mode"] = 0,0,
                        ["type"] = "WFrame",
                        ["level"] = 1025,0,
                    },
                },
                ["level"] = 1,0,
                ["sizepolicy"] = "full",
                ["geom"] = {
                    ["x"] = 0,0,
                    ["w"] = 1366,0,
                    ["h"] = 768,0,
                    ["y"] = 0,0,
                },
                ["unnumbered"] = true,
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["name"] = "*scratchws*",
                ["pseudomodal"] = true,
            },
        },
        ["name"] = "WScreen",
        ["type"] = "WScreen",
    },
}

