-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["name"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["level"] = 0,0,
                        ["geom"] = {
                            ["w"] = 1366,0,
                            ["h"] = 768,0,
                            ["y"] = 0,0,
                            ["x"] = 0,0,
                        },
                        ["name"] = "WTiling",
                        ["split_tree"] = {
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["name"] = "bigfuckingframe",
                                    ["managed"] = {
                                    },
                                    ["type"] = "WFrame",
                                    ["mode"] = 1,0,
                                },
                            },
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                            ["tls"] = 752,0,
                            ["type"] = "WSplitSplit",
                            ["brs"] = 16,0,
                        },
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                    },
                },
                ["level"] = 0,0,
                ["geom"] = {
                    ["w"] = 1366,0,
                    ["h"] = 768,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["name"] = "bigfuckingworkspace",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
                ["type"] = "WGroupWS",
            },
            [2] = {
                ["geom"] = {
                    ["w"] = 1366,0,
                    ["h"] = 768,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["level"] = 0,0,
                        ["geom"] = {
                            ["w"] = 1366,0,
                            ["h"] = 768,0,
                            ["y"] = 0,0,
                            ["x"] = 0,0,
                        },
                        ["name"] = "WTiling<1>",
                        ["split_tree"] = {
                            ["tl"] = {
                                ["tl"] = {
                                    ["tl"] = {
                                        ["type"] = "WSplitRegion",
                                        ["regparams"] = {
                                            ["name"] = "upperleft",
                                            ["managed"] = {
                                                [1] = {
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["windowid"] = 14680067,0,
                                                            ["level"] = 1,0,
                                                            ["bottom"] = true,
                                                            ["geom"] = {
                                                                ["w"] = 677,0,
                                                                ["h"] = 370,0,
                                                                ["y"] = 0,0,
                                                                ["x"] = 0,0,
                                                            },
                                                            ["checkcode"] = 4,0,
                                                            ["sizepolicy"] = "full",
                                                            ["type"] = "WClientWin",
                                                        },
                                                    },
                                                    ["level"] = 0,0,
                                                    ["geom"] = {
                                                        ["w"] = 677,0,
                                                        ["h"] = 370,0,
                                                        ["y"] = 3,0,
                                                        ["x"] = 3,0,
                                                    },
                                                    ["name"] = "WGroupCW<2>",
                                                    ["switchto"] = true,
                                                    ["type"] = "WGroupCW",
                                                    ["sizepolicy"] = "full",
                                                },
                                            },
                                            ["type"] = "WFrame",
                                            ["mode"] = 1,0,
                                        },
                                    },
                                    ["br"] = {
                                        ["type"] = "WSplitRegion",
                                        ["regparams"] = {
                                            ["name"] = "lowleft",
                                            ["managed"] = {
                                                [1] = {
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["windowid"] = 12582915,0,
                                                            ["level"] = 1,0,
                                                            ["bottom"] = true,
                                                            ["geom"] = {
                                                                ["w"] = 677,0,
                                                                ["h"] = 370,0,
                                                                ["y"] = 0,0,
                                                                ["x"] = 0,0,
                                                            },
                                                            ["checkcode"] = 5,0,
                                                            ["sizepolicy"] = "full",
                                                            ["type"] = "WClientWin",
                                                        },
                                                    },
                                                    ["level"] = 0,0,
                                                    ["geom"] = {
                                                        ["w"] = 677,0,
                                                        ["h"] = 370,0,
                                                        ["y"] = 3,0,
                                                        ["x"] = 3,0,
                                                    },
                                                    ["name"] = "WGroupCW<1>",
                                                    ["switchto"] = true,
                                                    ["type"] = "WGroupCW",
                                                    ["sizepolicy"] = "full",
                                                },
                                            },
                                            ["type"] = "WFrame",
                                            ["mode"] = 1,0,
                                        },
                                    },
                                    ["dir"] = "vertical",
                                    ["tls"] = 376,0,
                                    ["type"] = "WSplitSplit",
                                    ["brs"] = 376,0,
                                },
                                ["br"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["name"] = "righttt",
                                        ["managed"] = {
                                            [1] = {
                                                ["managed"] = {
                                                    [1] = {
                                                        ["windowid"] = 10485763,0,
                                                        ["level"] = 1,0,
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["w"] = 677,0,
                                                            ["h"] = 746,0,
                                                            ["y"] = 0,0,
                                                            ["x"] = 0,0,
                                                        },
                                                        ["checkcode"] = 6,0,
                                                        ["sizepolicy"] = "full",
                                                        ["type"] = "WClientWin",
                                                    },
                                                },
                                                ["level"] = 0,0,
                                                ["geom"] = {
                                                    ["w"] = 677,0,
                                                    ["h"] = 746,0,
                                                    ["y"] = 3,0,
                                                    ["x"] = 3,0,
                                                },
                                                ["name"] = "WGroupCW",
                                                ["switchto"] = true,
                                                ["type"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                            },
                                        },
                                        ["type"] = "WFrame",
                                        ["mode"] = 1,0,
                                    },
                                },
                                ["dir"] = "horizontal",
                                ["tls"] = 683,0,
                                ["type"] = "WSplitSplit",
                                ["brs"] = 683,0,
                            },
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                            ["tls"] = 752,0,
                            ["type"] = "WSplitSplit",
                            ["brs"] = 16,0,
                        },
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                    },
                },
                ["level"] = 0,0,
                ["sizepolicy"] = "full",
                ["name"] = "WGroupWS<1>",
                ["switchto"] = true,
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
                ["type"] = "WGroupWS",
            },
            [3] = {
                ["hidden"] = true,
                ["pseudomodal"] = true,
                ["name"] = "*scratchws*",
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["mode"] = 0,0,
                        ["managed"] = {
                        },
                        ["level"] = 1025,0,
                        ["bottom"] = true,
                        ["name"] = "*scratchpad*",
                        ["geom"] = {
                            ["w"] = 640,0,
                            ["h"] = 480,0,
                            ["y"] = 144,0,
                            ["x"] = 363,0,
                        },
                        ["type"] = "WFrame",
                        ["sizepolicy"] = "free_glue",
                    },
                },
                ["level"] = 1,0,
                ["geom"] = {
                    ["w"] = 1366,0,
                    ["h"] = 768,0,
                    ["y"] = 0,0,
                    ["x"] = 0,0,
                },
                ["unnumbered"] = true,
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
            },
        },
        ["type"] = "WScreen",
    },
}

